# Generated by Django 4.2.7 on 2024-01-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsettings',
            name='title',
            field=models.CharField(default=1, max_length=100, verbose_name='Название рассылки'),
            preserve_default=False,
        ),
    ]
