# Generated by Django 4.2.7 on 2024-01-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingmessage',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Тема письма'),
        ),
    ]
