# Generated by Django 4.2.7 on 2024-01-19 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_mailingsettings_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingsettings',
            options={'permissions': [('can_view_all_fields', 'Может просматривать всю админку')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
