# Generated by Django 4.2.7 on 2024-01-25 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0006_mailinglogger_setting_alter_mailinglogger_error'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingmessage',
            options={'ordering': ['id'], 'verbose_name': 'Письмо', 'verbose_name_plural': 'Письма'},
        ),
        migrations.AlterModelOptions(
            name='mailingsettings',
            options={'ordering': ['id'], 'permissions': [('can_view_all_fields', 'Может просматривать всю админку')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
