# Generated by Django 4.2.7 on 2024-01-18 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_all_fields', 'Может просматривать всю админку')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
