# Generated by Django 4.2.7 on 2024-01-19 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_all_fields', 'Может просматривать всю админку'), ('can_view_is_staff', 'Может просматривать персонал')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
