# Generated by Django 4.2.7 on 2024-01-18 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_comment_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('view_client_list', 'Может просматривать список клиентов')], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
